# Pandas Data Cleaning

Load data.

In [ ]:
# Importing Libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt  

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

## Handling Missing Data

#### Notes

- `df.dropna()`: Drop missing values.

##### Examples

Here we are only drop values if all of their values are missing.

In [2]:
df_cleaned = df.dropna(how='all')
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 86.2+ MB

Right now all we can do is drop values if they're missing. But that's not useful right now because our DataFrame didn't have any. 

So, what if we wanted to fill the missing values with something else? This is expecially useful so we don't run into errors when dealing with NaN values.

### Fillna

#### Notes

- `df.fillna()`: Fill missing values

#### Examples

Let's fill in instances where there's no salary info (aka these columns have NaN values `salary_rate`, `salary_year_avg`, `salary_hour_avg`) with 0.

We're going to look at a few rows in these 3 columns right now, so we can compare what we've done before to after. 

We'll use `iloc` to look at the first 10 rows `:20` and the salary information rows `11:14`.

In [11]:
df_cleaned.iloc[:10,11:14]

  salary_rate  salary_year_avg  salary_hour_avg
0        None              NaN              NaN
1        None              NaN              NaN
2        None              NaN              NaN
3        None              NaN              NaN
4        None              NaN              NaN
5        None              NaN              NaN
6        None              NaN              NaN
7        None              NaN              NaN
8        None              NaN              NaN
9        None              NaN              NaN

In [12]:
median_salary_year = df['salary_year_avg'].median()

In [13]:
median_salary_hour = df['salary_hour_avg'].median()

In [15]:
df_filled=df

df_filled['salary_year_avg'] = df['salary_year_avg'].fillna(median_salary_year)
df_filled['salary_hour_avg'] = df['salary_hour_avg'].fillna(median_salary_hour)

We fill the values for the 3 columns with 0 using `fillna()`.

In [16]:
df_filled.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        785741 non-null  float64
 13  salary_hour_avg        785741 non-null  float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 86.2+ MB

Now if we compare the results using `iloc` again on our new DataFrame. We see that the previous NaN values in the columns ( `salary_rate`, `salary_year_avg`, `salary_hour_avg`) have been replaced with 0.

In [17]:
df_filled.iloc[:10,11:14]

  salary_rate  salary_year_avg  salary_hour_avg
0        None         115000.0            45.98
1        None         115000.0            45.98
2        None         115000.0            45.98
3        None         115000.0            45.98
4        None         115000.0            45.98
5        None         115000.0            45.98
6        None         115000.0            45.98
7        None         115000.0            45.98
8        None         115000.0            45.98
9        None         115000.0            45.98

## Drop Duplicates

### Notes

* `drop_duplicates()`: Remove duplicate rows.
* Analysts will often need to clean up data and one of the most common issues we run into is duplicate values. 

### Examples

Now that we've dealt with NaN values. Let's continue cleaning the data by removing any duplicate rows.

In [18]:
df_unique = df_filled.drop_duplicates()
df_unique.info()

<class 'pandas.core.frame.DataFrame'>
Index: 785640 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785640 non-null  object
 1   job_title              785639 non-null  object
 2   job_location           784595 non-null  object
 3   job_via                785632 non-null  object
 4   job_schedule_type      772975 non-null  object
 5   job_work_from_home     785640 non-null  bool
 6   search_location        785640 non-null  object
 7   job_posted_date        785640 non-null  datetime64[ns]
 8   job_no_degree_mention  785640 non-null  bool
 9   job_health_insurance   785640 non-null  bool
 10  job_country            785591 non-null  object
 11  salary_rate            33066 non-null   object
 12  salary_year_avg        785640 non-null  float64
 13  salary_hour_avg        785640 non-null  float64
 14  company_name           785622 non-null  object
 15  job_skills             668654 non-null  object
 16  job_type_skills        668654 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 92.2+ MB

If you compare that with the original DataFrame which had 787686 entries. This new DataFrame `df_unique` has 787577 entries. It removed 109 entries. 

Now let's see what would happen if we tried to remove duplicates from `job_title`.

In [ ]:
df_unique = df_filled.drop_duplicates(subset=['job_title','company_name'])
df_unique.info()

<class 'pandas.core.frame.DataFrame'>
Index: 234674 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        234674 non-null  object
 1   job_title              234673 non-null  object
 2   job_location           234402 non-null  object
 3   job_via                234674 non-null  object
 4   job_schedule_type      230420 non-null  object
 5   job_work_from_home     234674 non-null  bool
 6   search_location        234674 non-null  object
 7   job_posted_date        234674 non-null  datetime64[ns]
 8   job_no_degree_mention  234674 non-null  bool
 9   job_health_insurance   234674 non-null  bool
 10  job_country            234642 non-null  object
 11  salary_rate            10217 non-null   object
 12  salary_year_avg        234674 non-null  float64
 13  salary_hour_avg        234674 non-null  float64
 14  company_name           234670 non-null  object
 15  job_skills             191817 non-null  object
 16  job_type_skills        191817 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 27.5+ MB

If we look at it now. It looks like we removed quite a few rows. Now all of these rows have unique `job_title`s.

In [21]:
print('Len of df_filled: ', len(df_filled))
print('Len df_unique:    ', len(df_unique))
print('Rows dropped:     ', len(df_filled) - len(df_unique))

Len of df_filled:  785741
Len df_unique:     234674
Rows dropped:      551067

In [20]:
df_unique.head(10)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,115000.0,45.98,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,115000.0,45.98,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,115000.0,45.98,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,115000.0,45.98,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,115000.0,45.98,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,None,115000.0,45.98,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,None,115000.0,45.98,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
7,Data Engineer,Data Engineer,Anywhere,via LinkedIn,Full-time,True,Romania,2023-12-07 13:40:49,False,False,Romania,None,115000.0,45.98,Zitec,"['sql', 'nosql', 'gcp', 'azure', 'aws', 'bigqu...","{'cloud': ['gcp', 'azure', 'aws', 'bigquery', ..."
8,Business Analyst,Technology & Operations Business Analyst,"Copenhagen, Denmark",via Trabajo.org,Full-time,False,Denmark,2023-06-05 13:44:34,False,False,Denmark,None,115000.0,45.98,Hempel,"['excel', 'powerpoint', 'power bi']","{'analyst_tools': ['excel', 'powerpoint', 'pow..."
9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,None,115000.0,45.98,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."